### ISSUE TITLE
Asynchronized Core

### ISSUE THREAD

**Issue by Morphan1** [DenizenScript/Denizen-Core#16]
I believe that certain core functions should be in a separate thread that doesn't lag the implementation. Things such as processing yaml and using commands that don't touch the implementation's API have no real reason to be in the main server thread. Anything that requires being on a Minecraft tick should take advantage of the server implementation's Scheduler.

This will most likely take a lot of time and effort, but I'm sure it will be worth it in the end. It could theoretically lower the chance of Denizen causing a server to crash because of a malfunctioning script and possibly be faster than any micro-optimizations we could make at this point.

**Comment by mcmonkey4eva** [comment]
Okay, go ahead and PR this magic full async rewrite then :)

I was actually thinking about this earlier and see no reasonable non-breaking way to accomplish it :/

I intend to rework Frenetic to be async-able though, as that has more room for it.

**Comment by Morphan1** [comment]
@mcmonkey4eva I don't understand the system flow as much as you do, especially in the core itself. I wouldn't know where to start. But I've thought about it a lot and after dealing with async code in another project recently, I realized it's a lot easier than it might seem.

What problems do you see with it?

**Comment by Morphan1** [comment]
This is slowly making progress now... Yay!

**Comment by mcmonkey4eva** [comment]
The core isn't async, but it's possible to do things async! That's a step!  Yay! Great work, Morphan!

**Comment by mcmonkey4eva** [comment]
haha async.

I mean improvements in this area would be nice, but they often come at the cost of performance for most users, and system complexity internally... both of which are kinda messy. It's also not really the most necessary improvement (how many scripters are going to have a legitimate use case for async and have the skill to use it safely? Non-zero, but not a remotely high number).

I really don't know how to cleanly transition Denizen 1 to work async reasonably well, especially given the majority of Spigot's code _hates_ async, and we'd have to be extremely careful about limiting the subset of things that work async.

Closing this because I'm closing all core issues. This is a bit too generalized of an issue (There's no specific fix or addition that resolves this issue, it's an overall long-term rework and forward-going awareness if anything) to really need to open as a new DenizenBukkit issue (which is now the issue tracker for D1Core issues as well, mostly just to simplify organization).
